<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBYWCetD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBYWCetD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBYWCetD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBYWCetD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBYWCetD\App_KernelDevDebugContainer([
    'container.build_hash' => 'BYWCetD',
    'container.build_id' => 'f0d25810',
    'container.build_time' => 1609957410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBYWCetD');
