<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'article' => [['id'], ['_controller' => 'App\\Controller\\ArticlesController::article'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'articleDelete' => [['id'], ['_controller' => 'App\\Controller\\ArticlesController::articleDelete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'articleUpdate' => [['id'], ['_controller' => 'App\\Controller\\ArticlesController::articleUpdate'], [], [['text', '/update'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'articles' => [[], ['_controller' => 'App\\Controller\\ArticlesController::articles'], [], [['text', '/articles']], [], []],
    'NewArticle' => [[], ['_controller' => 'App\\Controller\\ArticlesController::NewArticle'], [], [['text', '/articles/new']], [], []],
    'newComment' => [['id'], ['_controller' => 'App\\Controller\\CommentsController::newComment'], [], [['text', '/comment/new'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'deleteComment' => [['id', 'comment_id'], ['_controller' => 'App\\Controller\\CommentsController::deleteComment'], [], [['variable', '/', '[^/]++', 'comment_id', true], ['text', '/comments'], ['variable', '/', '[^/]++', 'id', true], ['text', '/article']], [], []],
    'Home' => [[], ['_controller' => 'App\\Controller\\DefaultController::home'], [], [['text', '/']], [], []],
    'About' => [[], ['_controller' => 'App\\Controller\\DefaultController::about'], [], [['text', '/about']], [], []],
    'Contacts' => [[], ['_controller' => 'App\\Controller\\DefaultController::contacts'], [], [['text', '/contacts']], [], []],
    'journal' => [[], ['_controller' => 'App\\Controller\\JournalController::index'], [], [['text', '/journal']], [], []],
    'LogOn' => [[], ['_controller' => 'App\\Controller\\UserController::isAuth'], [], [['text', '/logon']], [], []],
    'SignUp' => [[], ['_controller' => 'App\\Controller\\UserController::Registration'], [], [['text', '/signup']], [], []],
];
